// Ideally these props will be defined or autogenerated in a file
// Fetched at a high level provider

import { MessageNodeDataProp } from "./message";

export type NodeProp = {
    nodeId: number,
    type: string,
    data: MessageNodeDataProp,
    position: {
        top: number,
        left: number,
    },
    connection: number,
};